### ISSUE TITLE
Exit the REPL command missing on the README.md file

### ISSUE THREAD

**Issue by edhowland** [PeterCamilleri/fOOrth#122]
Hi,

I tried to run the REPL and got locked into an infinite loop because I could exit the interpreter with any command. (Please see my other issue on mini-readline issue tracker, wrt pressing Control-d to exit)
 The gforth program uses the 'bye' word to exit. What is it for fOOrth? Should not this bit of help be on the README.md?

Regards, Ed

**Comment by PeterCamilleri** [comment]
The commands are all described in the User's Guide, but the )quit command is the one you seek. I will try to add this to the readme file asap.

**Comment by PeterCamilleri** [comment]
This info has been added to the readme file in the git repository. It will be incorporated into the gem with the next release of fOOrth.
